In [290]:
import pandas as pd
import numpy as np

# **Leakage**

In [291]:
df= pd.read_excel('/content/LeakageReportExport - 2023-03-29T143723.940.xls')
df.head(5)

,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,Root Cause Issue Type,RAFM Involved in Change Management Process,Risk Accepted by Business,...,ParentID,sshIssue,Issue Type,Fraud Category,Fraud Type,Motive,Means,Method,BA Functionalities,BA Domain
0,2301,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,NaN,...,NaN,No,Revenue,NaN,NaN,NaN,NaN,NaN,Core - Customer Experience,Revenue and Cost Assurance
1,2301,MTN Irancell,R35.C01.A01,Inadequate customer verification,System failure,System Design,Resiliency Failures,Systemic,NaN,NaN,...,NaN,No,Revenue,NaN,NaN,NaN,NaN,NaN,Core - Customer Experience,Regulatory Assurance
2,2301,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,NaN,...,NaN,No,Revenue,NaN,NaN,NaN,NaN,NaN,Core - Customer Experience,Revenue and Cost Assurance
3,2301,MTN Irancell,R36.C01.A02,Inbound Interconnect Bypass: GSM Gateway,Fraud,A2P Fraud,Commercial,Systemic,NaN,NaN,...,NaN,No,Fraud,Subscriber Fraud,Abuse,The use of a mobile operator's products or ser...,Roaming Fraud - fraudsters exploit the time de...,"International Dialling (IRSF destinations), Ma...",NaN,Revenue and Cost Assurance
4,2301,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,NaN,...,NaN,No,Revenue,NaN,NaN,NaN,NaN,NaN,Core - Customer Experience,Revenue and Cost Assurance

In [292]:
 LeakageDetected=df['Local Currency Leakage Detected Value'].sum()
 LeakageDetected

5416614372

In [293]:
print(type(LeakageDetected))

<class 'numpy.int64'>

In [294]:
Revenue = input("Please Enter Your Revenue: ")

Please Enter Your Revenue: 25329292221954

In [295]:
print(type(Revenue))

<class 'str'>

In [296]:
R=int(Revenue)

In [297]:
LeakageCalculation =LeakageDetected/R
LeakageCalculation

0.0002138478376946192

In [298]:
LeakagePercent=LeakageCalculation/0.0015

In [299]:
LeakagePercent

0.14256522512974615

# Recovery

In [300]:
df1= pd.read_excel('/content/BenefitsReportExport (37).xls')
df1.head(5)

,Reporting Period,Realised Period,Operator,Control Reference,Risk Reference,Incident Reference,Benefit Type,Local Currency Value,US Dollar Value,Benefit Approval Status,...,IssueType,ParentID,Issue Type,Fraud Category,Fraud Type,Motive,Means,Method,BA Functionalities,BA Domain
0,2301,2301,MTN Irancell,R04.C01.A04,R04,EXP023409,Averted Loss,0.000000e+00,0,Not Submitted,...,Exposure,NaN,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2301,2301,MTN Irancell,R12.C01.A01,R12,EXP023383,Averted Loss,0.000000e+00,0,Not Submitted,...,Exposure,NaN,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2301,2301,MTN Irancell,R126.C03.A01,R126,EXP023414,Averted Loss,8.516662e+09,29709,Approved,...,Exposure,NaN,Fraud,Wholesale Fraud,Bypass Fraud,Terminate voice or SMS traffic as cheaply as p...,Bypass of the international gateways for inbou...,Traditional traffic Bypass,NaN,NaN
3,2301,2301,MTN Irancell,R26.C01.A02,R26,EXP023384,Averted Loss,1.030879e+09,3596,Approved,...,Exposure,NaN,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2301,2301,MTN Irancell,R58.C01.A02,R58,EXP023408,Averted Loss,4.420793e+09,15421,Approved,...,Exposure,NaN,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [301]:
    AddressableLeakage = df["Risk Category"].eq('Revenue Leakage','Cost Leakage')
    df2=df.loc[AddressableLeakage, 'newColumn'] = df.loc[AddressableLeakage, 'Local Currency Leakage Detected Value'].sum()
    df2

3478984137

In [302]:
    Recoveries = df1["Benefit Type"].eq('Recovered Revenue','Recovered Cost')
    df11=df1.loc[Recoveries, 'newColumn'] = df1.loc[Recoveries, 'Local Currency Value'].sum()
    df11

0.0

In [303]:
    AvertedLoss = df1["Benefit Type"].eq('Averted Loss')
    df12=df1.loc[AvertedLoss, 'newColumn'] = df1.loc[AvertedLoss, 'Local Currency Value'].sum()
    df12

14119340521.5

In [304]:
AddressableLeakagesAvertedLoss=df2+df12
RecoveriesAvertedLoss=df11 + df12
RecoveryRatio=RecoveriesAvertedLoss/AddressableLeakagesAvertedLoss
RecoveryRatio

0.802311628833393

# **MTTD**

In [305]:
df3= pd.read_excel('/content/RAMSReport.xlsx')
df3.head(5)

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,fraudRisk,leakageDetectedinUSD,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y
0,0,2301,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,396700668.0,Open,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance
1,1,2301,MTN Irancell,R35.C01.A01,Inadequate customer verification,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,170666532.0,Open,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Regulatory Assurance
2,2,2302,MTN Irancell,R35.C01.A01,Inadequate customer verification,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Regulatory Assurance
3,3,2302,MTN Irancell,R75.C01.A01,Unauthorized/inaccurate adjustments passed,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance
4,4,2302,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance

In [306]:
df31 =  df3.loc[(df3.IssueType == "Change Related")]
df31

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,fraudRisk,leakageDetectedinUSD,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,No,NaN,NaN,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,No,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,No,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance

In [307]:
from datetime import datetime
df31['identifiedDate'] = pd.to_datetime(df31['identifiedDate'])
df31['firstOccurrenceDate'] = pd.to_datetime(df31['firstOccurrenceDate'])

<ipython-input-307-c17074a1b943>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['identifiedDate'] = pd.to_datetime(df31['identifiedDate'])
<ipython-input-307-c17074a1b943>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['firstOccurrenceDate'] = pd.to_datetime(df31['firstOccurrenceDate'])

In [308]:
df31['MTTD']=df31['identifiedDate']-df31['firstOccurrenceDate']

<ipython-input-308-18da774749a3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['MTTD']=df31['identifiedDate']-df31['firstOccurrenceDate']

In [309]:
df31

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,leakageDetectedinUSD,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y,MTTD
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,NaN,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance,2 days
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,1 days
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,2 days

In [310]:
#df['days'] = df['duration'].dt.days
df31['MTTDNew']=df31['MTTD'].dt.days
df31

<ipython-input-310-844ffc444174>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['MTTDNew']=df31['MTTD'].dt.days

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y,MTTD,MTTDNew
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance,2 days,2
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,1 days,1
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,2 days,2

In [311]:
TotalLeakage=df31['Local Currency Leakage Detected Value'].sum()
TotalLeakage

3790627400

In [312]:
df31['Rate']=(df31['Local Currency Leakage Detected Value'])/TotalLeakage
df31

<ipython-input-312-7bce664706ca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['Rate']=(df31['Local Currency Leakage Detected Value'])/TotalLeakage

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y,MTTD,MTTDNew,Rate
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance,2 days,2,0.382206
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,1 days,1,0.192848
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,2 days,2,0.424946

In [313]:
df31['MTTDRate']= df31['Rate']*df31['MTTDNew']
MTDDCal=df31['MTTDRate'].sum()
MTDDCal

<ipython-input-313-cd6ded0ef59d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31['MTTDRate']= df31['Rate']*df31['MTTDNew']

1.8071516873433668

In [314]:
datatoexcel = pd.ExcelWriter('MTTD.xlsx')
df31.to_excel(datatoexcel)
datatoexcel.save()

# MTTR

In [315]:
df3= pd.read_excel('/content/RAMSReport.xlsx')
df3.head(5)

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,fraudRisk,leakageDetectedinUSD,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y
0,0,2301,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,396700668.0,Open,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance
1,1,2301,MTN Irancell,R35.C01.A01,Inadequate customer verification,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,170666532.0,Open,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Regulatory Assurance
2,2,2302,MTN Irancell,R35.C01.A01,Inadequate customer verification,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Regulatory Assurance
3,3,2302,MTN Irancell,R75.C01.A01,Unauthorized/inaccurate adjustments passed,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance
4,4,2302,MTN Irancell,R05.C01.A01,Poor Product performance,System failure,System Design,Resiliency Failures,Systemic,NaN,...,No,NaN,NaN,Draft,Customer Services,Systemic,MTNIRN,tagName1:NotSpecified,Core - Customer Experience,Revenue and Cost Assurance

In [316]:
df32 =  df3.loc[(df3.IssueType == "Change Related")]
df32

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,fraudRisk,leakageDetectedinUSD,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,No,NaN,NaN,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,No,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,No,NaN,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance

In [317]:
from datetime import datetime
df32['identifiedDate'] = pd.to_datetime(df32['identifiedDate'])
df32['lastOccuranceDate'] = pd.to_datetime(df32['lastOccuranceDate'])

<ipython-input-317-d57a90302497>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df32['identifiedDate'] = pd.to_datetime(df32['identifiedDate'])
<ipython-input-317-d57a90302497>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df32['lastOccuranceDate'] = pd.to_datetime(df32['lastOccuranceDate'])

In [318]:
df32['MTTR']=df32['lastOccuranceDate']-df32['identifiedDate']

<ipython-input-318-694dfba1bb55>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df32['MTTR']=df32['lastOccuranceDate']-df32['identifiedDate']

In [319]:
df32['MTTRNew']=df32['MTTR'].dt.days
df32

<ipython-input-319-e431c1b2e1f6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df32['MTTRNew']=df32['MTTR'].dt.days

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,leakageDetectedLocalValue,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y,MTTR,MTTRNew
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance,-2 days,-2
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,8 days,8
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,NaN,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,-2 days,-2

In [320]:
TotalLeakage=df32['Local Currency Leakage Detected Value'].sum()
TotalLeakage

3790627400

In [321]:
df32['Rate']=(df32['Local Currency Leakage Detected Value'])/TotalLeakage
df32

<ipython-input-321-5c02ca478ac1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df32['Rate']=(df32['Local Currency Leakage Detected Value'])/TotalLeakage

,Unnamed: 0,Reporting Period,Operator,Control Reference,Risk Name,Root Cause 1,Root Cause 2,Root Cause 3,IssueType,RAFM Involved in Change Management Process,...,Status,businessFunction,issueType,businessUnit,Tags_y,BA Functionalities_y,BA Domain_y,MTTR,MTTRNew,Rate
10,10,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System failure,System Implementation,NaN,Change Related,NaN,...,Draft,Information Systems,Change Related,MTNIRN,tagName1:NotSpecified,NaN,Revenue and Cost Assurance,-2 days,-2,0.382206
12,12,2302,MTN Irancell,R05.C01.A02,Poor Product performance,System failure,System Implementation,NaN,Change Related,NaN,...,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,8 days,8,0.192848
13,13,2302,MTN Irancell,R55.C02.A03,Error in configuration of xDR generation param...,System Configuration and provisioning,Process Failure,Process Failure,Change Related,NaN,...,Draft,Networks,Change Related,MTNIRN,tagName1:NotSpecified,Core - Revenue and Cost Assurance,Revenue and Cost Assurance,-2 days,-2,0.424946

In [322]:
df32 = df32._get_numeric_data()
df32[df32 < 0] = 0
df32

,Unnamed: 0,Reporting Period,RAFM Involved in Change Management Process,Risk Accepted by Business,Reason,Comments,Local Currency Leakage Detected Value,US Dollar Leakage Detected Value,Local Currency Recoverable Leakage Detected Value,US Dollar Recoverable Leakage Value,ParentID,leakageDetectedinUSD,leakageDetectedLocalValue,MTTRNew,Rate
10,10,2302,NaN,NaN,NaN,NaN,1448800201,5053.88,0,0.0,NaN,NaN,NaN,0,0.382206
12,12,2302,NaN,NaN,NaN,NaN,731016098,2550.02,0,0.0,NaN,NaN,NaN,8,0.192848
13,13,2302,NaN,NaN,NaN,NaN,1610811101,5619.02,0,0.0,NaN,NaN,NaN,0,0.424946

In [323]:
df32['MTTRRate']= df32['Rate']*df32['MTTRNew']

In [324]:
MTTRCal=df32['MTTRRate'].sum()
MTTRCal

1.5427865012530644

In [325]:
datatoexcel = pd.ExcelWriter('MTTR.xlsx')
df32.to_excel(datatoexcel)
datatoexcel.save()

# **FOM**
****

In [326]:
BAMaturity = input("Please Enter Your BAMaturity score: ")

Please Enter Your BAMaturity score: 1.44

In [327]:
BAMaturity=float(BAMaturity)

In [328]:
if 0.0 <= BAMaturity < 0.25:
   BAweight=1
elif   0.25<= BAMaturity < 0.5 :
   BAweight=1.5
elif  0.5<= BAMaturity <0.75 :
   BAweight=2  
elif  0.75<= BAMaturity <1.0 :
   BAweight=2.5
elif  1.0<= BAMaturity <1.25 :
   BAweight=3
elif  1.25<= BAMaturity <1.5 : 
   BAweight=3.5
elif  1.5<= BAMaturity <1.75 : 
   BAweight=4
elif  1.75<= BAMaturity <2.0 :  
   BAweight=4.5
elif  2.0<= BAMaturity <2.25 : 
   BAweight=5
elif  2.25<= BAMaturity <2.5 :
   BAweight=5.5
elif  2.5<= BAMaturity <2.75 :
   BAweight=6
elif  2.75<= BAMaturity <3.0 :
   BAweight=6.5
elif  3.0<= BAMaturity <3.25 : 
   BAweight=7
elif  3.25<= BAMaturity <3.5 :
   BAweight=7.5
elif  3.5<= BAMaturity <3.75 :
   BAweight=8 
elif  3.75<= BAMaturity <4.0 :
   BAweight=8.5     
elif  4.0<= BAMaturity <4.25 :
   BAweight=9
elif  4.25<= BAMaturity <4.5 : 
   BAweight=9.5 
elif   BAMaturity == 4.5 :
   BAweight=10

In [329]:
BAweight

3.5

In [330]:
RAMaturity = input("Please Enter Your RAMaturity score: ")

Please Enter Your RAMaturity score: 4.45

In [331]:
RAMaturity=float(RAMaturity)

In [332]:
if 0.0 <= RAMaturity < 0.25:
   RAweight=1
elif   0.25<= RAMaturity < 0.5 :
   RAweight=1.5
elif  0.5<= RAMaturity <0.75 :
   RAweight=2  
elif  0.75<= RAMaturity <1.0 :
   RAweight=2.5
elif  1.0<= RAMaturity <1.25 :
   RAweight=3
elif  1.25<= RAMaturity <1.5 : 
   RAweight=3.5
elif  1.5<= RAMaturity <1.75 : 
   RAweight=4
elif  1.75<= RAMaturity <2.0 :  
   RAweight=4.5
elif  2.0<= RAMaturity <2.25 : 
   RAweight=5
elif  2.25<= RAMaturity <2.5 :
   RAweight=5.5
elif  2.5<= RAMaturity <2.75 :
   RAweight=6
elif  2.75<= RAMaturity <3.0 :
   RAweight=6.5
elif  3.0<= RAMaturity <3.25 : 
   RAweight=7
elif  3.25<= RAMaturity <3.5 :
   RAweight=7.5
elif  3.5<= RAMaturity <3.75 :
   RAweight=8 
elif  3.75<= RAMaturity <4.0 :
   RAweight=8.5     
elif  4.0<= RAMaturity <4.25 :
   RAweight=9
elif  4.25<= RAMaturity <4.5 : 
   RAweight=9.5 
elif   RAMaturity == 4.5 :
   RAweight=10

In [333]:
RAweight

9.5

In [334]:
if   0.01<= RecoveryRatio < 0.055 :
   Recweight=1
elif  0.055<= RecoveryRatio <0.1 :
   Recweight=1.5  
elif  0.1<= RecoveryRatio <0.15 :
   Recweight=2
elif  0.15<= RecoveryRatio <0.2 :
   Recweight=2.5
elif  0.2<= RecoveryRatio <0.25 : 
   Recweight=3
elif  0.25<= RecoveryRatio <0.3 : 
   Recweight=3.5
elif  0.3<= RecoveryRatio <0.35 :  
   Recweight=4
elif  0.35<= RecoveryRatio <0.4 : 
   Recweight=4.5
elif  0.4<= RecoveryRatio <0.45 :
   Recweight=5
elif  0.45<= RecoveryRatio <0.5 :
   Recweight=5.5
elif  0.5<= RecoveryRatio <0.55 :
   Recweight=6
elif  0.55<= RecoveryRatio <0.6 : 
   Recweight=6.5
elif  0.6<= RecoveryRatio <0.65 :
   Recweight=7
elif  0.65<= RecoveryRatio <0.7 :
   Recweight=7.5 
elif  0.7<= RecoveryRatio <0.75 :
   Recweight=8     
elif  0.75<= RecoveryRatio <0.8 :
   Recweight=8.5
elif  0.8<= RecoveryRatio <0.85 : 
   Recweight=9 
elif  0.85<= RecoveryRatio <0.9 : 
   Recweight=9.5 
elif   RecoveryRatio == 0.9 :
   Recweight=10

In [335]:
Recweight

9

In [336]:
Residual = input("Please Enter Your Residual score: ")

Please Enter Your Residual score: 0.3

In [337]:
Residual=float(Residual)

In [338]:
if  0.3<= Residual <0.35 :
   Resweight=1  
elif  0.35<= Residual <0.4 :
   Resweight=1.5
elif  0.4<= Residual <0.45 :
   Resweight=2
elif  0.45<= Residual <0.5 : 
   Resweight=2.5
elif  0.5<= Residual <0.55 : 
   Resweight=3
elif  0.55<= Residual <0.6 :  
   Resweight=3.5
elif  0.6<= Residual <0.65 : 
   Resweight=4
elif  0.65<= Residual <0.7 :
   Resweight=4.5
elif  0.7<= Residual <0.75 :
   Resweight=5
elif  0.75<= Residual <0.8 :
   Resweight=5.5
elif  0.8<= Residual <0.85 : 
   Resweight=6
elif  0.85<= Residual <0.9 :
   Recweight=6.5
elif  0.9<= Residual <0.95 :
   Resweight=7 
elif  0.95<= Residual <1.0 :
   Resweight=7.5     
elif  1.0<= Residual <1.05 :
   Resweight=8
elif  1.05<= Residual <1.1 : 
   Resweight=8.5 
elif  1.1<= Residual <1.15 : 
   Resweight=9
elif  1.15<= Residual <1.2:
    Resweight=9.5  
elif   Residual == 1.2 :
   Resweight=10

In [339]:
Resweight

1

In [340]:
if  50.0<= MTTRCal <47.5 :
   MTTRweight=1
elif  47.5<= MTTRCal <45.0 :
   MTTRweight=1.5
elif  45.0<= MTTRCal <42.5 : 
   MTTRweight=2
elif  42.5<= MTTRCal <40.0 : 
   MTTRweight=2.5
elif  40.0<= MTTRCal <37.5 :  
   MTTRweight=3
elif  37.5<= MTTRCal <35.0 : 
   MTTRweight=3.5
elif 35.0<= MTTRCal <32.5 :
   MTTRweight=4
elif  32.5<= MTTRCal <30.0 :
   MTTRweight=4.5
elif  30.0<= MTTRCal <27.5 :
   MTTRweight=5
elif  27.5<= MTTRCal <25.0 : 
   MTTRweight=5.5
elif  25.0<= MTTRCal <22.5 :
   MTTRweight=6
elif  22.5<= MTTRCal <20.0 :
   MTTRweight=6.5 
elif  20.0<= MTTRCal <17.5 :
   MTTRweight=7     
elif  17.5<= MTTRCal <15.0 :
   MTTRweight=7.5
elif  15.0<= MTTRCal <12.5 : 
   MTTRweight=8 
elif  12.5<= MTTRCal <10.0 : 
   MTTRweight=8.5
elif  10.0<= MTTRCal <7.5:
    MTTRweight=9  
elif  7.5<= MTTRCal <5.0: 
    MTTRweight=9.5
elif   MTTRCal <= 5.0 :
   MTTRweight=10

In [341]:
MTTRweight

10

In [342]:
if  50.0<= MTDDCal <47.5 :
   MTTDweight=1
elif  47.5<= MTDDCal <45.0 :
   MTTDweight=1.5
elif  45.0<= MTDDCal <42.5 : 
   MTTDweight=2
elif  42.5<= MTDDCal <40.0 : 
   MTTDweight=2.5
elif  40.0<= MTDDCal <37.5 :  
   MTTDweight=3
elif  37.5<= MTDDCal <35.0 : 
   MTTDweight=3.5
elif 35.0<= MTDDCal <32.5 :
   MTTDweight=4
elif  32.5<= MTDDCal <30.0 :
   MTTDweight=4.5
elif  30.0<= MTDDCal <27.5 :
   MTTDweight=5
elif  27.5<= MTDDCal <25.0 : 
   MTTDweight=5.5
elif  25.0<= MTDDCal <22.5 :
   MTTDweight=6
elif  22.5<= MTDDCal <20.0 :
   MTTDweight=6.5 
elif  20.0<= MTDDCal <17.5 :
   MTTDweight=7     
elif  17.5<= MTDDCal <15.0 :
   MTTDweight=7.5
elif  15.0<= MTDDCal <12.5 : 
   MTTDweight=8 
elif  12.5<= MTDDCal <10.0 : 
   MTTDweight=8.5
elif  10.0<= MTDDCal <7.5:
    MTTDweight=9  
elif  7.5<= MTDDCal <5.0: 
    MTTDweight=9.5
elif   MTDDCal <= 5.0 :
   MTTDweight=10

In [343]:
MTTDweight

10

In [344]:
if   0.0<= LeakagePercent < 0.23 :
   Lekweight=1
elif  0.23<= LeakagePercent <0.25 :
   Lekweight=1.5  
elif  0.25<= LeakagePercent <0.3 :
   Lekweight=2
elif  0.3<= LeakagePercent <0.35 :
   Lekweight=2.5
elif  0.35<= LeakagePercent <0.4 : 
   Lekweight=3
elif  0.4<= LeakagePercent <0.45 : 
   Lekweight=3.5
elif  0.45<= LeakagePercent <0.5 :  
   Lekweight=4
elif  0.5<= LeakagePercent <0.55 : 
   Lekweight=4.5
elif  0.55<= LeakagePercent <0.6 :
   Lekweight=5
elif  0.6<= LeakagePercent <0.65 :
   Lekweight=5.5
elif  0.65<= LeakagePercent <0.7 :
   Lekweight=6
elif  0.7<= LeakagePercent <0.75 : 
   Lekweight=6.5
elif  0.75<= LeakagePercent <0.8 :
   Lekweight=7
elif  0.8<= LeakagePercent <0.85 :
   Lekweight=7.5 
elif  0.85<= LeakagePercent <0.9 :
   Lekweight=8     
elif  0.9<= LeakagePercent <0.95 :
   Lekweight=8.5
elif  0.95<= LeakagePercent <0.98 : 
   Lekweight=9 
elif  0.98<= LeakagePercent <1.0 : 
   Lekweight=9.5 
elif   LeakagePercent == 1.0 :
   Lekweight=10

In [345]:
Lekweight

1

In [346]:
FOM=(BAweight*0.2)+(RAweight*0.2)+(Recweight*0.15)+(Resweight*0.3)+(MTTDweight*0.05)+(MTTRweight*0.05)+(Lekweight*0.05)

In [347]:
FOM

5.3